spring.datasource:
  url: jdbc:postgresql://localhost:5432/course_work
  username: postgres
  password: postgres
  hikari:
    connectionTimeout: 20000
    maximumPoolSize: 5

spring:
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false
    open-in-view: false
  thymeleaf:
    cache: false
  flyway:
    enabled: false

